"""kyc_ve_yil_guncellemesi

Revision ID: 746bc919eade
Revises: ea2e373e4fc8
Create Date: 2026-05-11 11:00:30.804082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746bc919eade'
down_revision: Union[str, None] = 'ea2e373e4fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tc_kimlik_no', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('mersis_no', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_users_tc_kimlik_no'), 'users', ['tc_kimlik_no'], unique=True)
    op.create_unique_constraint(None, 'users', ['mersis_no'])
    op.alter_column('watches', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watches', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_tc_kimlik_no'), table_name='users')
    op.drop_column('users', 'mersis_no')
    op.drop_column('users', 'tc_kimlik_no')
    # ### end Alembic commands ###
