"""NVI_kimlik_dogrulama

Revision ID: d333af093dda
Revises: 746bc919eade
Create Date: 2026-05-15 13:26:44.946061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd333af093dda'
down_revision: Union[str, None] = '746bc919eade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrow_transactions', sa.Column('delivery_method', sa.Enum('SHIPPING', 'STORE_PICKUP', name='delivery_method'), nullable=True))
    op.add_column('escrow_transactions', sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'BANK_TRANSFER', name='payment_method'), nullable=True))
    op.add_column('escrow_transactions', sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('escrow_transactions', 'discount_amount')
    op.drop_column('escrow_transactions', 'payment_method')
    op.drop_column('escrow_transactions', 'delivery_method')
    # ### end Alembic commands ###
