"""initial schema

Revision ID: da4f64e539a0
Revises: 
Create Date: 2026-05-10 14:22:50.073370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da4f64e539a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('BUYER', 'SELLER', 'EXPERT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('watches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('reference_number', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('box_papers', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'MINT', 'EXCELLENT', 'GOOD', 'FAIR', name='watch_condition'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'SOLD', 'REJECTED', name='watch_status'), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('ai_processing_status', sa.Enum('NONE', 'QUEUED', 'PROCESSING', 'DONE', 'FAILED', name='ai_processing_status'), nullable=False),
    sa.Column('ai_processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watches_ai_processing_status'), 'watches', ['ai_processing_status'], unique=False)
    op.create_index(op.f('ix_watches_brand'), 'watches', ['brand'], unique=False)
    op.create_index(op.f('ix_watches_model'), 'watches', ['model'], unique=False)
    op.create_index(op.f('ix_watches_reference_number'), 'watches', ['reference_number'], unique=False)
    op.create_index(op.f('ix_watches_seller_id'), 'watches', ['seller_id'], unique=False)
    op.create_index(op.f('ix_watches_slug'), 'watches', ['slug'], unique=True)
    op.create_table('ai_valuations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watch_id', sa.UUID(), nullable=False),
    sa.Column('estimated_value_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_value_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_version', sa.String(length=40), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_valuations_watch_id'), 'ai_valuations', ['watch_id'], unique=False)
    op.create_table('auctions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watch_id', sa.UUID(), nullable=False),
    sa.Column('starting_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reserve_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('buy_it_now_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_bid_increment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'ENDED', 'COMPLETED', 'CANCELLED', name='auction_status'), nullable=False),
    sa.Column('winning_bid_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_bid_id'], ['bids.id'], name='fk_auction_winning_bid', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_id')
    )
    op.create_index(op.f('ix_auctions_ends_at'), 'auctions', ['ends_at'], unique=False)
    op.create_table('authenticity_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watch_id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('AUTHENTIC', 'SERVICE_PARTS', 'NOT_AUTHENTIC', 'INCONCLUSIVE', name='authenticity_verdict'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_id')
    )
    op.create_table('watch_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watch_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_images_watch_id'), 'watch_images', ['watch_id'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('max_proxy_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_auction_id'), 'bids', ['auction_id'], unique=False)
    op.create_index(op.f('ix_bids_bidder_id'), 'bids', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_bids_placed_at'), 'bids', ['placed_at'], unique=False)
    op.create_table('escrow_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'FUNDED', 'AWAITING_AUTHENTICATION', 'AUTHENTICATED', 'SHIPPED_TO_BUYER', 'DELIVERED', 'RELEASED', 'REFUNDED', 'DISPUTED', name='escrow_status'), nullable=False),
    sa.Column('payment_provider_ref', sa.String(length=120), nullable=True),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escrow_transactions')
    op.drop_index(op.f('ix_bids_placed_at'), table_name='bids')
    op.drop_index(op.f('ix_bids_bidder_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_auction_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_watch_images_watch_id'), table_name='watch_images')
    op.drop_table('watch_images')
    op.drop_table('authenticity_certificates')
    op.drop_index(op.f('ix_auctions_ends_at'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_ai_valuations_watch_id'), table_name='ai_valuations')
    op.drop_table('ai_valuations')
    op.drop_index(op.f('ix_watches_slug'), table_name='watches')
    op.drop_index(op.f('ix_watches_seller_id'), table_name='watches')
    op.drop_index(op.f('ix_watches_reference_number'), table_name='watches')
    op.drop_index(op.f('ix_watches_model'), table_name='watches')
    op.drop_index(op.f('ix_watches_brand'), table_name='watches')
    op.drop_index(op.f('ix_watches_ai_processing_status'), table_name='watches')
    op.drop_table('watches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
