"""sync_delivery_code

Revision ID: ea2e373e4fc8
Revises: da4f64e539a0
Create Date: 2026-05-10 23:19:04.819322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2e373e4fc8'
down_revision: Union[str, None] = 'da4f64e539a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_auction_winning_bid', 'auctions', 'bids', ['winning_bid_id'], ['id'], use_alter=True)
    op.add_column('watches', sa.Column('delivery_code', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_watches_delivery_code'), 'watches', ['delivery_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watches_delivery_code'), table_name='watches')
    op.drop_column('watches', 'delivery_code')
    op.drop_constraint('fk_auction_winning_bid', 'auctions', type_='foreignkey')
    # ### end Alembic commands ###
